version: '3'

services:
  project1:
    build:
      context: ./python-internship
    command:
      - bash
      - -c
      - |
        python -m internship migrate --no-input
        python -m internship collectstatic --no-input
        python -m internship runserver 0.0.0.0:8001
    env_file:
      - ./python-internship/.env
    volumes:
      - ./python-internship/static:/app/static


  project2:
    build:
      context: ./ebs-python-internship-test
    volumes:
      - ./ebs-python-internship-test/static:/app/static


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./python-internship/static:/app/static
      - ./ebs-python-internship-test/static:/app/static


  postgres:
    image: postgres:latest
    hostname: postgres.internship.com
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
